services:
    anavaro.activenotifications.maincontroller:
        class: anavaro\activenotifications\controller\main_controller
        arguments:
            - '@user'
            - '@request'
            - '@notification_manager'
            - '%tables.notifications%'
            - '@dbal.conn'
            - '@template'
            - '@path_helper'
    anavaro.activenotifications.listener:
        class: anavaro\activenotifications\event\listener
        arguments:
            - '@config'
            - '@user'
            - '@template'
            - '@notification_manager'
            - '@controller.helper'
        tags:
            - { name: event.listener }
